version: '3.3'
services:
  db:
    image: postgres
    ports:
      - '5440:5432'
    env_file:
      - ./.env
    environment:
      POSTGRES_DB: '${DB_DATABASE}'
      POSTGRES_USER: '${DB_USER}'
      POSTGRES_PASSWORD: '${DB_PASSWORD}'
    volumes:
      - postgres-data-blog:/var/lib/postgresql/data


volumes:
  postgres-data-blog:
